# Generated by Django 3.2.15 on 2022-09-18 19:00

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('map', cloudinary.models.CloudinaryField(default='placeholder_map', max_length=255, verbose_name='map')),
                ('image_one', cloudinary.models.CloudinaryField(default='placeholder_one', max_length=255, verbose_name='image_one')),
                ('image_two', cloudinary.models.CloudinaryField(default='placeholder_two', max_length=255, verbose_name='image_two')),
                ('difficulty', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('distance', models.CharField(max_length=10)),
                ('ave_speed', models.CharField(max_length=20)),
                ('up', models.CharField(max_length=10)),
                ('down', models.CharField(max_length=10)),
                ('published_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='blog_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
