# Generated by Django 3.2.15 on 2022-09-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='years_riding',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
