# Generated by Django 3.2.16 on 2022-11-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_years_riding'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_removed',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
